import axios from "axios";
import type { NextPage } from "next";
import Head from "next/head";
import React, { useContext } from "react";
import Recipes from "../components/Recipes";
import Box from "@mui/material/Box";
import AppContext from "../components/AppContext";
import Nav from "../components/Nav";
import Router from 'next/router'

const RecipeReviewCard: NextPage = props => {
  const [recipes, setRecipes] = React.useState([]);
  const value = useContext(AppContext);
  const { id, direction, siteTitle} = value.state.languages;

  const getRecipes = () => {
    axios({ url: "recipes/", method: "get" }).then((response) => {
      if (response && response?.data?.success === true) {
        setRecipes(response?.data?.result);
      }
    });
  }
  
  const htmlContent = React.useMemo(getRecipes, [id])

  React.useEffect(()=> htmlContent, [id])

  React.useEffect(()=>{
    const {pathname} = Router
    if(pathname == '/' ){
       Router.push('/en/recipes')
    }
  },[])

  return (
    <div>
      <Head>
        <title>{siteTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <Box sx={{
        margin:'0 auto',
        width:'70%',
        padding:10,
        direction:direction
      }}>
        {recipes?.length &&
          recipes.map((recipe) => <Recipes key={recipe.id} recipe={recipe} />)}
      </Box>
    </div>
  );
};

export default RecipeReviewCard;
